services:                                                                                                        
  app:                                                                                                           
    build:                                                                                                       
      context: .                                                                                                 
      dockerfile: Dockerfile                                                                                     
    env_file: ".env"
    depends_on:                                                                                                  
      - db                                                                                                       
    networks:                                                                                                    
      - app-network                                                                                              
                                                                                                                 
  db:                                                                                                            
    image: postgres:13
    env_file: ".env"
    volumes:                                                                                                     
      - postgres_data:/var/lib/postgresql/data
    networks:                                                                                                    
      - app-network                                                                                              
                                                                                                                 
  nginx:                                                                                                         
    image: nginx:latest
    volumes:                                                                                                     
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/sveno/certificate.cer:/etc/ssl/sveno/certificate.cer                                            
      - /etc/ssl/sveno/private.key:/etc/ssl/sveno/private.key                                                    
    ports:                                                                                                       
      - "80:80"
      - "443:443"
    depends_on:                                                                                                  
      - app                                                                                                      
    networks:                                                                                                    
      - app-network                                                                                              
                                                                                                                 
networks:                                                                                                        
  app-network:                                                                                                   
    driver: bridge                                                                                               
                                                                                                                 
volumes:                                                                                                         
  postgres_data:                                                                                                 
    driver: local 
